// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwoqwekaywpvgiwgprqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3b3F3ZWtheXdwdmdpd2dwcnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzgyNDMsImV4cCI6MjA3MzI1NDI0M30.OsvpnR1byo2uByhoWKT6BaFJqRDF-mazDe9vypz_mXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
